### ISSUE TITLE
scrapeulous service isn't working

### ISSUE THREAD

**Issue by M0rrisChang** [NikolaiT/scrapeulous#3]
Hi there,
I've been using scrapeulous to scrape google search engine for a while.
Last time I made use of it was around 1 or 2 weeks ago. Just now, it's not working anymore.
It's not responding no matter how I tune the parameters so I went to the web site and tried the demo api for google scraper, not responding either.
Please check it out...

**Comment by NikolaiT** [comment]
Hi there!

We try to keep down time as little as possible, but sometimes we need to push a new version of the backend, so you might experience small downtimes.

Sorry for that.
